"""'20210729'
修改內容如下:
- 新增table follow。
Revision ID: 3bc06d715a3b
Revises: 7f8e3c1f91bb
Create Date: 2021-07-29 12:21:18.766271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bc06d715a3b'
down_revision = '7f8e3c1f91bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_index(op.f('ix_follow_timestamp'), 'follow', ['timestamp'], unique=False)
    op.alter_column('posts', 'body',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='內文',
               existing_nullable=True)
    op.alter_column('posts', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='時戳',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment='時戳',
               existing_nullable=True)
    op.alter_column('posts', 'body',
               existing_type=mysql.TEXT(),
               comment='內文',
               existing_nullable=True)
    op.drop_index(op.f('ix_follow_timestamp'), table_name='follow')
    op.drop_table('follow')
    # ### end Alembic commands ###
