"""'20210802'
- 新增column: posts.body_html。
Revision ID: dd6819dcd6fc
Revises: 3bc06d715a3b
Create Date: 2021-08-02 05:57:21.166945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6819dcd6fc'
down_revision = '3bc06d715a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # 修改排列順序
    command = 'alter table posts modify column body_html text after body'
    op.execute(command)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
